# Generated by Django 6.0.5 on 2026-05-18 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('capacidad_max', models.IntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion_hito', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('noche', 'Por Noche'), ('estadia', 'Por Estadía')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CabanaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('es_principal', models.BooleanField(default=False)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.cabana')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('fecha_checkin', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('bloqueo_temporal', 'Bloqueo Temporal')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.cabana')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.cabana')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extra')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras_reservados', to='api.reserva')),
            ],
        ),
    ]
